server:
  port: 80

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3366/querydsl_practice
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace